FROM php:7.0-fpm

RUN apt-get update && apt-get install -y \
    curl \
    libmcrypt-dev \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng12-dev \
    libxslt-dev

RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/

RUN docker-php-ext-install \
    pdo_mysql \
    xsl \
    soap \
    mbstring \
    mcrypt \
    xsl \
    zip \
    opcache \
    gd

RUN apt-get install -y libicu-dev

RUN docker-php-ext-configure intl && \
    docker-php-ext-install intl

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
    php composer-setup.php --install-dir=/usr/local/bin --filename=composer && \
    php -r "unlink('composer-setup.php');"

ADD ./*.ini /usr/local/etc/php/conf.d/
ADD ./app.pool.conf /usr/local/etc/php/conf.d/

ADD ./script/* /tmp/

RUN chmod +x /tmp/*.sh

RUN chown -R www-data:www-data /usr/local/etc/php/conf.d

RUN usermod -u 1000 www-data

USER www-data:www-data

WORKDIR /var/www

ARG MAGENTO_VERSION=2.1.10
ENV MAGENTO_VERSION ${MAGENTO_VERSION}

RUN export MAGENTO_VERSION=${MAGENTO_VERSION}

EXPOSE 9000
